### ISSUE TITLE
I cannot get this to work in Linux Mint???

### ISSUE THREAD

**Issue by phd21** [hank/dsf2flac#16]
Hi Hank,

Although it seems rare to need a program for this nowadays. I had a request from a Linux Mint member for a program or app to do this. So, I researched a lot and found your application.

I found archive files in the link below which I tried all of them, and none of them would work "dsf2flac: command not found".

So I went through the effort of compiling this in my Linux Mint 18.2 KDE system based on Ubuntu 16.04, and after successfully compiling, it still would not work and I got the same message?

Also I cannot find any of these type of files to test, do you know where I can download some?

Can you help with this?

Regards,
Phil
phd21

**Comment by phd21** [comment]
Hi Hank,

As soon as I read another article post that said I had to use "./dsf2flac", it worked. And, it is fast. I also found what appears to be a GUI front-end from Sonore..

Sonore - DSD2FLAC - converts DSD files to FLAC
http://www.sonore.us/dsd2flac.html

Regards,
Phil
phd21

**Comment by hank** [comment]
Oh seems like you solved it. Cool!!

On Mar 3, 2018, Phil <notifications@github.com> wrote:
>Hi Hank,
>
>As soon as I read another article post that said I had to use
>"./dsf2flac", it worked. And, it is fast. I also found what appears to
>be a GUI front-end from Sonore..
>
>Sonore - DSD2FLAC - converts DSD files to FLAC
>http://www.sonore.us/dsd2flac.html
>
>Regards,
>Phil
>phd21

-- Erik

**Comment by hank** [comment]
I'm on vacation at the moment until the middle of the month, but after that I can probably take a look!

On Mar 3, 2018, Phil <notifications@github.com> wrote:
>Hi Hank,
>
>Although it seems rare to need a program for this nowadays. I had a
>request from a Linux Mint member for a program or app to do this. So, I
>researched a lot and found your application.
>
>I found archive files in the link below which I tried all of them, and
>none of them would work "dsf2flac: command not found".
>
>So I went through the effort of compiling this in my Linux Mint 18.2
>KDE system based on Ubuntu 16.04, and after successfully compiling, it
>still would not work and I got the same message?
>
>Also I cannot find any of these type of files to test, do you know
>where I can download some?
>
>Can you help with this?
>
>Regards,
>Phil
>phd21

-- Erik
