### ISSUE TITLE
loadlocale.c:129 error

### ISSUE THREAD

**Issue by 1271** [hank/dsf2flac#19]
Hi. I have this error for some files.

```bash
dsf2flac: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
```

Version: https://github.com/hank/dsf2flac/commit/b0cf5aa6ddc60df9bbfeed25548e443c99f5cb16

DSF file: https://drive.google.com/open?id=1S3c7epnI4tq4lCNVsZT7nMax5qQ3Tyqv

Format: DSFl
Bitrate: 22579 Kb/s
Freq: 1411200 Hz
Ch: 2

Thank!

**Comment by jackocleebrown** [comment]
Hi,
I downloaded and tested the file you attached and it converted without any problems on my system. I think that this error is related to a locale setting on your computer. Please can you run the command "locale" in your terminal and post the output.

**Comment by 1271** [comment]
Oh! Thank! This can really be a problem.
I think I will fix it myself later.

**Comment by xchg-dot-ca** [comment]
I have similar issue ( **dsf2flac 0.1Rev51** ) and do not know what to do:
`dsf2flac: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed. `

my locale output is:

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by davygrvy** [comment]
$ export LC_ALL=C
