### ISSUE TITLE
Can't completely do make on Ubuntu 20.04

### ISSUE THREAD

**Issue by yvikt** [hank/dsf2flac#23]
<pre>
vic@HP:~/dsf2flac$ master sudo ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Generating configuration files for dsf2flac, please wait ...
Ignore all non-fatal warnings ...

configure.ac:10: installing './ar-lib'
configure.ac:10: installing './compile'
configure.ac:11: installing './config.guess'
configure.ac:11: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:10: installing './compile'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ANSI C header files... (cached) yes
checking id3.h usability... yes
checking id3.h presence... yes
checking for id3.h... yes
checking for ID3Tag_New in -lid3... yes
checking whether pkg-config knows about taglib >= 1.6... ok
checking whether pkg-config knows about flac >= 1.3... ok
checking whether pkg-config knows about flac++ >= 1.3... ok
checking for boostlib >= 1.48... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Timer library is available... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for memory.h... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for int16_t... yes
checking for int32_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working strtod... yes
checking for memset... yes
checking for pow... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/libdstdec/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
sucesses
vic@HP:~/dsf2flac$ master sudo make
make  all-recursive
make[1]: вход в каталог «/home/vic/dsf2flac»
Making all in src
make[2]: вход в каталог «/home/vic/dsf2flac/src»
Making all in libdstdec
make[3]: вход в каталог «/home/vic/dsf2flac/src/libdstdec»
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-ccp_calc.o -MD -MP -MF .deps/libdstdec_a-ccp_calc.Tpo -c -o libdstdec_a-ccp_calc.o `test -f 'ccp_calc.c' || echo './'`ccp_calc.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-ccp_calc.Tpo .deps/libdstdec_a-ccp_calc.Po
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-dst_ac.o -MD -MP -MF .deps/libdstdec_a-dst_ac.Tpo -c -o libdstdec_a-dst_ac.o `test -f 'dst_ac.c' || echo './'`dst_ac.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-dst_ac.Tpo .deps/libdstdec_a-dst_ac.Po
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-dst_data.o -MD -MP -MF .deps/libdstdec_a-dst_data.Tpo -c -o libdstdec_a-dst_data.o `test -f 'dst_data.c' || echo './'`dst_data.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-dst_data.Tpo .deps/libdstdec_a-dst_data.Po
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-dst_fram.o -MD -MP -MF .deps/libdstdec_a-dst_fram.Tpo -c -o libdstdec_a-dst_fram.o `test -f 'dst_fram.c' || echo './'`dst_fram.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-dst_fram.Tpo .deps/libdstdec_a-dst_fram.Po
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-dst_init.o -MD -MP -MF .deps/libdstdec_a-dst_init.Tpo -c -o libdstdec_a-dst_init.o `test -f 'dst_init.c' || echo './'`dst_init.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-dst_init.Tpo .deps/libdstdec_a-dst_init.Po
gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/taglib   -fpermissive -g -O2 -I/usr/include/taglib   -MT libdstdec_a-unpack_dst.o -MD -MP -MF .deps/libdstdec_a-unpack_dst.Tpo -c -o libdstdec_a-unpack_dst.o `test -f 'unpack_dst.c' || echo './'`unpack_dst.c
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
mv -f .deps/libdstdec_a-unpack_dst.Tpo .deps/libdstdec_a-unpack_dst.Po
rm -f libdstdec.a
ar cru libdstdec.a libdstdec_a-ccp_calc.o libdstdec_a-dst_ac.o libdstdec_a-dst_data.o libdstdec_a-dst_fram.o libdstdec_a-dst_init.o libdstdec_a-unpack_dst.o 
ar: модификатор «u» игнорируется, так как по умолчанию используется «D» (смотрите «U»)
ranlib libdstdec.a
make[3]: выход из каталога «/home/vic/dsf2flac/src/libdstdec»
make[3]: вход в каталог «/home/vic/dsf2flac/src»
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT cmdline.o -MD -MP -MF .deps/cmdline.Tpo -c -o cmdline.o cmdline.cpp
mv -f .deps/cmdline.Tpo .deps/cmdline.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT dsd_decimator.o -MD -MP -MF .deps/dsd_decimator.Tpo -c -o dsd_decimator.o dsd_decimator.cpp
mv -f .deps/dsd_decimator.Tpo .deps/dsd_decimator.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT dsdiff_file_reader.o -MD -MP -MF .deps/dsdiff_file_reader.Tpo -c -o dsdiff_file_reader.o dsdiff_file_reader.cpp
mv -f .deps/dsdiff_file_reader.Tpo .deps/dsdiff_file_reader.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT dsd_sample_reader.o -MD -MP -MF .deps/dsd_sample_reader.Tpo -c -o dsd_sample_reader.o dsd_sample_reader.cpp
mv -f .deps/dsd_sample_reader.Tpo .deps/dsd_sample_reader.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT dsf_file_reader.o -MD -MP -MF .deps/dsf_file_reader.Tpo -c -o dsf_file_reader.o dsf_file_reader.cpp
mv -f .deps/dsf_file_reader.Tpo .deps/dsf_file_reader.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT filters.o -MD -MP -MF .deps/filters.Tpo -c -o filters.o filters.cpp
mv -f .deps/filters.Tpo .deps/filters.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT fstream_plus.o -MD -MP -MF .deps/fstream_plus.Tpo -c -o fstream_plus.o fstream_plus.cpp
mv -f .deps/fstream_plus.Tpo .deps/fstream_plus.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
mv -f .deps/main.Tpo .deps/main.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT tagConversion.o -MD -MP -MF .deps/tagConversion.Tpo -c -o tagConversion.o tagConversion.cpp
mv -f .deps/tagConversion.Tpo .deps/tagConversion.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include -I/usr/include -O3 -Wall -I/usr/include/taglib    -g -O2 -MT dop_packer.o -MD -MP -MF .deps/dop_packer.Tpo -c -o dop_packer.o dop_packer.cpp
mv -f .deps/dop_packer.Tpo .deps/dop_packer.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -L/usr/lib -L/usr/lib/x86_64-linux-gnu  -lboost_filesystem -lboost_system   -o dsf2flac cmdline.o dsd_decimator.o dsdiff_file_reader.o dsd_sample_reader.o dsf_file_reader.o filters.o fstream_plus.o main.o tagConversion.o dop_packer.o   -lid3 libdstdec/libdstdec.a -ltag -lFLAC -lFLAC++ -lFLAC
libtool: link: g++ -g -O2 -o dsf2flac cmdline.o dsd_decimator.o dsdiff_file_reader.o dsd_sample_reader.o dsf_file_reader.o filters.o fstream_plus.o main.o tagConversion.o dop_packer.o  -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lboost_filesystem -lboost_system /usr/lib/x86_64-linux-gnu/libid3.so libdstdec/libdstdec.a -ltag -lFLAC++ -lFLAC
/usr/bin/ld: main.o: in function `boost::timer::cpu_timer::cpu_timer()':
/usr/include/boost/timer/timer.hpp:61: undefined reference to `boost::timer::cpu_timer::start()'
/usr/bin/ld: main.o: in function `checkTimer(double, double)':
/home/vic/dsf2flac/src/main.cpp:79: undefined reference to `boost::timer::cpu_timer::elapsed() const'
/usr/bin/ld: main.o: in function `boost::timer::cpu_timer::cpu_timer()':
/usr/include/boost/timer/timer.hpp:61: undefined reference to `boost::timer::cpu_timer::start()'
/usr/bin/ld: /usr/include/boost/timer/timer.hpp:61: undefined reference to `boost::timer::cpu_timer::start()'
/usr/bin/ld: /usr/include/boost/timer/timer.hpp:61: undefined reference to `boost::timer::cpu_timer::start()'
/usr/bin/ld: /usr/include/boost/timer/timer.hpp:61: undefined reference to `boost::timer::cpu_timer::start()'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:455: dsf2flac] Ошибка 1
make[3]: выход из каталога «/home/vic/dsf2flac/src»
make[2]: *** [Makefile:514: all-recursive] Ошибка 1
make[2]: выход из каталога «/home/vic/dsf2flac/src»
make[1]: *** [Makefile:414: all-recursive] Ошибка 1
make[1]: выход из каталога «/home/vic/dsf2flac»
make: *** [Makefile:346: all] Ошибка 2
vic@HP:~/dsf2flac$ master 

</pre>

**Comment by yvikt** [comment]
Before that I have done this
<pre>
sudo apt install libid3-tools libid3-3.8.3-dev libtag1-dev libflac++-dev libflac-dev libboost-dev libboost-filesystem-dev
</pre>

**Comment by hank** [comment]
I have a feeling you need to replace libboost with an older version. See `apt search libboost` for options.

**Comment by hank** [comment]
Also at some point it looks like `-lboost_timer` became necessary potentially. Try adding that to the link command.

**Comment by yvikt** [comment]
Thanks for your answer, but ~~I'm not a hacker~~ I lack qualifications )))
Which exactly version do I need? There are a lot of them.
Also tried on Ubuntu 16.04 
Same problem :(
<pre>
main.o: In function `setupTimer(double)':
/usr/include/boost/timer/timer.hpp:62: undefined reference to `boost::timer::cpu_timer::start()'
main.o: In function `checkTimer(double, double)':
/home/vic/dsf2flac/src/main.cpp:79: undefined reference to `boost::timer::cpu_timer::elapsed() const'
main.o: In function `checkTimer(double, double)':
/usr/include/boost/timer/timer.hpp:62: undefined reference to `boost::timer::cpu_timer::start()'
main.o: In function `do_pcm_conversion(DsdSampleReader*, int, int, bool, double, boost::filesystem::path, boost::filesystem::path, bool)':
/usr/include/boost/timer/timer.hpp:62: undefined reference to `boost::timer::cpu_timer::start()'
main.o: In function `do_dop_conversion(DsdSampleReader*, boost::filesystem::path, boost::filesystem::path)':
/usr/include/boost/timer/timer.hpp:62: undefined reference to `boost::timer::cpu_timer::start()'
main.o: In function `_GLOBAL__sub_I__Z10setupTimerd':
/usr/include/boost/timer/timer.hpp:62: undefined reference to `boost::timer::cpu_timer::start()'
collect2: error: ld returned 1 exit status
Makefile:448: recipe for target 'dsf2flac' failed
make[3]: *** [dsf2flac] Error 1
make[3]: выход из каталога «/home/vic/dsf2flac/src»
Makefile:502: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: выход из каталога «/home/vic/dsf2flac/src»
Makefile:414: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: выход из каталога «/home/vic/dsf2flac»
Makefile:346: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by spvkgn** [comment]
Try to install `libboost-timer-dev` package.

Here is deb built on 20.04 
[dsf2flac_0.1+git20180101.b0cf5aa-1_amd64.deb.gz](https://github.com/hank/dsf2flac/files/5950959/dsf2flac_0.1%2Bgit20180101.b0cf5aa-1_amd64.deb.gz)

**Comment by yvikt** [comment]
> Try to install `libboost-timer-dev` package.
> 
> Here is deb built on 20.04
> [dsf2flac_0.1+git20180101.b0cf5aa-1_amd64.deb.gz](https://github.com/hank/dsf2flac/files/5950959/dsf2flac_0.1%2Bgit20180101.b0cf5aa-1_amd64.deb.gz)

Thank you very much. I solved my issue with installing deb package you have mentioned and
<pre> apt install libboost-chrono1.71.0 libboost-timer1.71.0 </pre>
It works !

**Comment by brianherman** [comment]
Can I submit your deb package to ubuntu for you? @yvikt  or can you submit the deb to ubuntu or debian package guys?

**Comment by yvikt** [comment]
Honestly this is not my deb package )
