### ISSUE TITLE
extras/picard dsf file support not working on MusicBrainz Picard 1.3.2

### ISSUE THREAD

**Issue by leico** [hank/dsf2flac#8]
![2016-10-20 19 49 49](https://cloud.githubusercontent.com/assets/1610962/19556979/a989ddb2-96fe-11e6-9523-87ff39ebd342.png)

**Comment by jackocleebrown** [comment]
Take a look here: https://github.com/aidan-g/dsf2flac/commit/b611125ec3766fdd0beba978af3239bd808b347d

**Comment by erwjack** [comment]
Hi Hank,
please, could you update the plugin to avoid the error mentioned above?
I tried to use the update from aidan-g but it does not work, it generates bad id3v2 tags, unreadables with - for example - mp3tag.
Thank in advance!

EJ

**Comment by hank** [comment]
I'm not currently working on this code, and I'm not familiar with Picard. I'm happy to perform pull requests if you make one that works for you. Sorry I can't commit the time at the moment.

**Comment by jackocleebrown** [comment]
Fixed #11
