### ISSUE TITLE
[Question] Sample rate

### ISSUE THREAD

**Issue by trinaldi** [hank/dsf2flac#9]
Hi, this is a really great tool and a time saver, thanks!

I was going through the source code and the docs but I couldn't find anything about getting the output FLAC with a 96kHz (96000Hz) sample rate, just the ones mentioned [here](https://github.com/hank/dsf2flac/blob/a9ff4cad7668d3867eb69feca074a1c5ce5c85dd/src/cmdline.cpp#L39) . 

Is it possible?

Thanks

**Comment by hank** [comment]
Thanks for the feedback, glad you like it. I don't know any reason why you wouldn't be able to add to that possible sample rate array and generate output with 96khz. I would say try it and add to this ticket if it fails for some reason!

**Comment by trinaldi** [comment]
It's actually common to see audio files with that sample rate and 24bit depth. Of course, you'd had to have perfect hearing to notice the difference. It's just a curiosity/study question!

I'll try it myself, thanks for the pointer :)

**Comment by jackocleebrown** [comment]
Unfortunately it is not totally straight forward to add support for 96kHz. DSD sample rate is always at a multiple of 44.1kHz, so the conversion to another multiple of 44.1kHz (88.2kHz, 176.4kHz etc) is easier and more direct than a multiple of 48kHz (such as 96kHz). It is possible to add support but it would require quite a bit of work.

**Comment by trinaldi** [comment]
@jackocleebrown Oh, you're right.
I forgot about this specification! It's been a while since I downloaded my last SACD. I'm reading the docs and articles as we speak

**Comment by jackocleebrown** [comment]
Yes, just one of those things. If you're really keen to get 96kHz files then I'd suggest you do it in two steps. First use DSF2FLAC to get 352.8kHz data, then downsample to 96kHz using another tool (for example sox). 

This fork has a nice mod that pipes the flac data directly to stdout and this could be piped directly into sox for conversion to 96k: https://github.com/denius/dsf2flac/commit/3763e286abc227bae7c5ad1745f7bb89dfb3bae8

**Comment by trinaldi** [comment]
Thanks again for the help, guys.
I'll chek this repo, @jackocleebrown , but I'm afraid the audio would lose some of its natural characteristics by resampling with another multiplier

**Comment by jackocleebrown** [comment]
@trinaldi I agree, better to stick with a multiple of 44.1k and do as little processing as possible.
